// components/Centered.vue
<template>
  <div
    :class="`flex items-center ${start ? 'justify-start' : 'justify-center'} ${
      row ? 'flex-row' : 'flex-col'
    } ${bg ? 'bg-background' : ''} w-screen h-screen`"
  >
    <slot />
  </div>
</template>

<script lang="ts" setup>
defineProps<{
  row?: boolean;
  start?: boolean;
  bg?: boolean;
}>();
</script>

// src/layouts/Centered.tsx
export type LayoutProps = {
  children: any | any[];
  className?: string;
  row?: boolean;
  start?: boolean;
};

export function Centered(props: LayoutProps) {
  return (
    <div
      className={`flex items-center ${
        props.start ? "justify-start" : "justify-center"
      } ${props.row ? "flex-row" : "flex-col"} w-screen min-h-screen ${
        props.className ?? ""
      }`}
    >
      {props.children}
    </div>
  );
}
